import React, {useEffect, useState} from 'react';
import {Menu, X, ArrowUpRight} from 'lucide-react';

const impact=[['100+','Paying B2B customers'],['1,000','Users in 3 months'],['5x','Product downloads'],['30+','AI systems built'],['₦10B','Revenue'],['$500K','Transaction value'],['$30,000','In revenue'],['47,000','LinkedIn followers']];
const results=[
  {client:'KOPPOH',context:'EDTECH · PRODUCT MARKETING',headline:'FROM ZERO TO 100+ CUSTOMERS.',metrics:[['100+','PAYING B2B CUSTOMERS'],['60x','ROAS'],['1M+','IMPRESSIONS']],copy:'Built Koppoh’s go-to-market engine from the ground up, bringing together positioning, lead generation, CRM, lead scoring and automated conversion systems to build a repeatable path from prospect to customer.'},
  {client:'DRIVEWELL',context:'AI CAR-TECH · GO-TO-MARKET',headline:'1,000 USERS. THREE MONTHS.',metrics:[['1,000','USERS ACQUIRED'],['$20K','PARTS REVENUE']],copy:'Helped take Drivewell from zero to its first 1,000 users by combining customer research, positioning and multi-channel acquisition to find the product’s early market.'},
  {client:'ACCINVEST',context:'B2B · PERFORMANCE MARKETING',headline:'LOWER COST. BETTER ACQUISITION.',metrics:[['25%','LOWER CPL'],['10x','LINKEDIN ADS ROAS'],['2x','CLIENT ACQUISITION'],['10+','B2B PARTNERSHIPS']],copy:'Built paid acquisition, outbound and account-based campaigns focused on reaching the right businesses, creating qualified opportunities and improving the economics of customer acquisition.'},
  {client:'WHOOSH',context:'PRODUCT MARKETING',headline:'GROWTH ACROSS THE FUNNEL.',metrics:[['5x','DOWNLOAD GROWTH'],['400%','ACTIVATION GROWTH'],['250%','SIGN-UP GROWTH'],['30%','LOWER CHURN']],copy:'Used product marketing to improve how customers discovered, understood and adopted the product, contributing to stronger downloads, activation and sign-ups while reducing churn.'},
  {client:'TBT AGRO',context:'AGRITECH · GO-TO-MARKET',headline:'$500K IN LAUNCH WEEK.',metrics:[['$500K','LAUNCH-WEEK VOLUME'],['3','INTERNATIONAL MARKETS']],copy:'Supported the go-to-market launch of a technology-enabled agricultural marketplace, helping build demand and acquire customers across the US, Netherlands and China.'},
  {client:'WORKAHOLIC360',context:'B2B SALES · GTM',headline:'10,000+ PROSPECTS.',metrics:[['10,000+','COMPANIES'],['50%+','SHOW-RATE IMPROVEMENT']],copy:'Built a 10,000+ company prospect database and helped develop the outbound and CRM infrastructure used to find, qualify and convert B2B opportunities.'},
  {client:'BRIDGE & LINK ASSOCIATES',context:'COMMERCIAL · LEAD GENERATION',headline:'₦10B IN DEAL VALUE.',metrics:[['5','COMMERCIAL DEALS'],['₦10B','AGGREGATE VALUE']],copy:'Marketing and lead-generation work contributed to five commercial deals worth approximately ₦10 billion in aggregate value.'}
];
const speakingEvents=['TEDxTanke','TEDxUniOsun','LinkedIn Local Ekpoma','LinkedIn Local BootCon','LinkedIn Local UNN','LinkedIn Local Akure','LinkedIn Local Kaduna','LinkedIn Local Abeokuta'];
const organized=[
  ['01','LINKEDIN LOCAL JOS','CONVENER','Hosted the largest LinkedIn Local event in Northern Nigeria, bringing more than 500 people together around careers, digital skills and opportunity.'],
  ['02','LINKEDIN LOCAL NIGERIA','TEAM MANAGEMENT LEAD','Helped lead the organizing team behind a national LinkedIn gathering focused on connecting young professionals and creating opportunities for learning and growth.'],
  ['03','JAMIE PAJOEL INTERNATIONAL','VICE PRESIDENT','Served as Vice President, Plateau State contributing to the planning and organization of the event and its wider community.'],
  ['04','AI GTM AFRICA','FOUNDER & CONVENER','Building an upcoming five-city platform bringing founders, operators and business leaders together around AI, go-to-market and growth across African markets.']
];
const partnerWhatsApp=`https://wa.me/2349025631654?text=${encodeURIComponent("Hi Williams, I'd like to partner with you for AI GTM Africa.")}`;

function ProfileHeader(){
  const [open,setOpen]=useState(false);
  return <header className="profile-nav"><a className="brand" href="/#top">AI GTM <b>AFRICA</b></a><nav className={open?'open':''} aria-label="Profile navigation"><a href="#profile" onClick={()=>setOpen(false)}>Profile</a><a href="#results" onClick={()=>setOpen(false)}>Results</a><a href="#tedx" onClick={()=>setOpen(false)}>TEDx</a><a href="#organized" onClick={()=>setOpen(false)}>Convening</a><a href="#speaking" onClick={()=>setOpen(false)}>Speaking</a><a className="profile-back" href="/">Event Website <span className="cta-arrow"/></a></nav><button className="menu" aria-expanded={open} aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
}

export default function TomidePage(){
  useEffect(()=>{window.scrollTo(0,0);const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[]);
  return <div className="profile-page"><ProfileHeader/><main>
    <section className="bio-hero dark"><div className="bio-hero-media"><img src="/images/profile/tedx-tanke.jpg" alt="Tomide Williams speaking at TEDxTanke"/></div><div className="bio-hero-shade"/><div className="bio-hero-copy reveal"><p className="kicker">PRODUCT MARKETING · AI &amp; GTM · PUBLIC SPEAKING</p><h1>TOMIDE<br/>WILLIAMS.</h1><div className="bio-hero-meta"><span>FOUNDER, AI GTM AFRICA</span><span>TWO-TIME TEDx SPEAKER</span></div></div></section>

    <section id="profile" className="bio-intro light profile-section"><div className="bio-intro-title reveal"><p className="kicker">MY PRACTICE</p><h2>BUILDING PRODUCTS, GO-TO-MARKET SYSTEMS AND AI.</h2></div><div className="bio-intro-body reveal"><p className="profile-lead">Tomide Williams is a product marketing leader, AI and go-to-market practitioner, product builder and public speaker.</p><p>He works across product, marketing, technology and growth — taking products from early ideas to market, building customer acquisition systems, leading launches and applying AI to the way businesses market, sell and operate.</p><p>His experience spans customer research, product positioning, go-to-market strategy, demand generation, B2B acquisition, sales systems, CRM, automation and AI implementation.</p></div><div className="bio-impact">{impact.map(([n,l],i)=><article className="reveal" style={{transitionDelay:`${i*70}ms`}} key={n+l}><strong>{n}</strong><span>{l}</span></article>)}</div></section>

    <section id="results" className="results-section light profile-section"><div className="bio-section-head reveal"><p className="kicker">MY SELECTED RESULTS</p><h2>MY WORK.<br/>WHAT IT DELIVERED.</h2></div><div className="results-list">{results.map((result,i)=><article className="result-record reveal" style={{transitionDelay:`${i*80}ms`}} key={result.client}><div className="result-identity"><span>{String(i+1).padStart(2,'0')}</span><div><p>{result.context}</p><h3>{result.client}</h3></div></div><div className="result-story"><h3>{result.headline}</h3><p>{result.copy}</p></div><div className="result-metrics">{result.metrics.map(([value,label])=><div key={value+label}><strong>{value}</strong><span>{label}</span></div>)}</div></article>)}</div></section>

    <section id="tedx" className="tedx-section dark profile-section"><div className="bio-section-head reveal"><p className="kicker">MY TEDx TALKS</p><h2>TWO TALKS.<br/>TWO IDEAS.</h2></div><div className="tedx-grid"><a className="tedx-feature reveal" href="https://www.youtube.com/watch?v=jYEEjzmLj_A" target="_blank" rel="noreferrer"><figure><img src="/images/profile/tedx-tanke.jpg" alt="Tomide Williams delivering The Hidden Cost of AI in Marketing at TEDxTanke"/><figcaption><span>01 / TEDxTANKE</span><ArrowUpRight/></figcaption></figure><h3>THE HIDDEN COST OF AI</h3><p>AI can make marketing faster without necessarily making it better. The talk examines what businesses risk losing when speed and automation come at the expense of customer understanding, strategy and judgment.</p></a><a className="tedx-feature reveal" href="https://www.youtube.com/watch?v=SaR0oJY_3qs" target="_blank" rel="noreferrer"><figure><img src="/images/profile/tedx-uniosun.jpg" alt="Tomide Williams speaking about the creator economy at TEDxUniOsun"/><figcaption><span>02 / TEDxUNIOSUN</span><ArrowUpRight/></figcaption></figure><h3>THE RISE OF THE CREATOR ECONOMY</h3><p>The creator economy is changing how people turn knowledge and expertise into opportunity. The talk explores how storytelling, niche communities and trust can create new paths to economic value.</p></a></div></section>

    <section id="organized" className="organized-section light profile-section"><div className="bio-section-head reveal"><p className="kicker">EVENTS I HAVE ORGANIZED</p><h2>BUILDING ROOMS THAT MATTER.</h2></div><div className="organized-layout"><figure className="organized-photo reveal"><img src="/images/profile/linkedin-local-jos.jpg" alt="Tomide Williams hosting LinkedIn Local Jos"/><figcaption>LINKEDIN LOCAL JOS / PLATEAU STATE</figcaption></figure><div className="organized-list">{organized.map(([num,title,role,copy],i)=><article className="reveal" style={{transitionDelay:`${i*90}ms`}} key={title}><span>{num}</span><div><p className="organized-role">{role}</p><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>

    <section id="speaking" className="speaking-record dark profile-section"><div className="bio-section-head reveal"><p className="kicker">MY SELECTED SPEAKING</p><h2>FROM LINKEDIN LOCALS TO TEDx</h2></div><div className="speaking-record-layout"><figure className="speaking-record-photo reveal"><img src="/images/profile/speaking-collage.jpg" alt="Tomide Williams at a speaking engagement"/><figcaption>PUBLIC SPEAKING / COMMUNITY / IMPACT</figcaption></figure><div className="speaking-event-list">{speakingEvents.map((event,i)=><div className="reveal" style={{transitionDelay:`${(i%4)*60}ms`}} key={event}><span>{String(i+1).padStart(2,'0')}</span><h3>{event}</h3></div>)}</div></div></section>

    <section className="practice-section light profile-section"><div className="bio-section-head reveal"><p className="kicker">MY WORK</p><h2>PRODUCT. GTM. AI.</h2></div><div className="practice-record"><article className="reveal"><span>01</span><h3>PRODUCT &amp; POSITIONING</h3><p>I research customers, clarify market problems, define positioning and shape messaging that helps products communicate their value clearly. I carry that thinking through launches, adoption and sales enablement.</p></article><article className="reveal"><span>02</span><h3>GO-TO-MARKET</h3><p>I build the systems that connect positioning, demand generation, acquisition, sales and retention. This includes channel strategy, conversion funnels, CRM, lead management and performance measurement.</p></article><article className="reveal"><span>03</span><h3>AI IMPLEMENTATION</h3><p>I build AI agents, CRM systems, automations and internal tools around real business needs. Each system is designed to reduce manual work, improve follow-up or help teams make faster decisions.</p></article></div></section>

    <section className="profile-origin dark profile-section"><div className="bio-section-head reveal"><p className="kicker">WHY AI GTM AFRICA</p><h2>AI FOR AFRICAN BUSINESS.</h2></div><div className="profile-prose reveal"><p>AI GTM Africa grew from a pattern Tomide has seen repeatedly while working with products and businesses: companies have access to increasingly powerful AI, but often struggle to connect it to the problems that actually matter.</p><p>The platform brings together <strong>AI, product marketing and go-to-market</strong> to help founders and operators understand their customers, build better products and create more effective ways to reach the market.</p><p>It is built around practical work — real businesses, real problems and systems that can be tested, built and put to use.</p><a className="cta" href={partnerWhatsApp} target="_blank" rel="noreferrer">Partner with Tomide <span className="cta-arrow"/></a></div></section>
  </main><footer className="profile-footer dark"><a className="brand" href="/">AI GTM <b>AFRICA</b></a><p>© 2026 AI GTM Africa</p><a href="/#cities">View 2026 Cities</a></footer></div>;
}
